test get version

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,7 +27,10 @@ jobs:
       - name: Fetch latest version
         id: get_latest_version
         run: |
-          latest_version=$(curl -s https://api.github.com/repos/lesserkuma/FlashGBX/releases/latest | grep '"tag_name":' | awk -F\" '{print $4}')
+          latest_version=$(curl -s https://api.github.com/repos/lesserkuma/FlashGBX/releases/latest | grep '"tag_name":' | awk -F\" '{print $4}') || {
+            echo "Error fetching latest version information"
+            exit 1
+          }
           echo "Latest version: $latest_version"
           export latest_version="$latest_version"
           
